### ISSUE TITLE
publish to npm and make sure we can be used with browserify

### ISSUE THREAD

**Issue by bartvde** [boundlessgeo/ole#11]
We'll also need to publish a minified and a debug version.

**Comment by bartvde** [comment]
Trying to use the library through browserify does not work currently:

```
Barts-MacBook-Air:foo bartvandeneijnden$ browserify index.js
SyntaxError: /private/tmp/foo/node_modules/ole/dist/ole.js: Unexpected token (38:6)
  36 | });foStyleFunctions = this._convertLabelingInfo(layerInfo.labelingInfo, mapUnits);
  37 |         styleFunctions = styleFunctions.concat(labelingInfoStyleFunctions);
> 38 |       }
     |       ^
  39 |       if (styleFunctions.length === 1) {
  40 |         return styleFunctions[0];
  41 |       } else {
    at Parser.pp.raise (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/private/tmp/foo/node_modules/ole/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:79:19)
```

**Comment by bartvde** [comment]
When switching to a newer version of babelify I get a different error:

```
Error: Cannot find module './StyleGenerator.js' from '/private/tmp/foo/node_modules/ole/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:42:25
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by bartvde** [comment]
This looks similar though we are already using standalone: https://github.com/substack/node-browserify/issues/374

**Comment by bartvde** [comment]
Forgot we still need to publish to npm. This commit only resolves the loading through browserify.

**Comment by bartvde** [comment]
it seems that because we define the babelify transform in the browserify key in package.json, that all projects that use us through npm will need it?

**Comment by bartvde** [comment]
indeed this is the case, which is kind of unwanted behaviour

**Comment by bartvde** [comment]
also the output of watchify is slightly different from browserify and is messing up the dist directory

**Comment by bartvde** [comment]
okay so let's try moving babelify to dependencies

**Comment by bartvde** [comment]
That indeed does the trick.
Now it's better to separate the output of browserify and watchify

**Comment by bartvde** [comment]
okay this is now done with https://github.com/boundlessgeo/ole/commit/69bbf39c0c7b7a863fe8b917406fc1bd846144bc
