### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by JasonFitz** [boundlessgeo/ole#15]
here is the error log when I ran npm run build:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ole@0.6.1
6 info build ole@0.6.1
7 verbose unsafe-perm in lifecycle true
8 info ole@0.6.1 Failed to exec build script
9 verbose stack Error: ole@0.6.1 build: `npm-run-all --parallel build:min build:debug`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ole@0.6.1
11 verbose cwd C:\Users\jfitzsimmons\Desktop\ole-master
12 error Windows_NT 6.1.7601
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error ole@0.6.1 build: `npm-run-all --parallel build:min build:debug`
17 error Exit status 1
18 error Failed at the ole@0.6.1 build script 'npm-run-all --parallel build:min build:debug'.
18 error This is most likely a problem with the ole package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm-run-all --parallel build:min build:debug
18 error You can get their info via:
18 error     npm owner ls ole
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by bartvde** [comment]
Sorry about the delay, I will check this in my Windows VM soon.
In the meantime, you should be able to use the distribution files: https://github.com/boundlessgeo/ole/tree/master/dist
